run_tmb: Compile with -O1 under windows #12
At -O3, we were getting:

  undefined reference to `__gxx_personality_sj0'

...whilst the internet suggests this is mismatched error handling,
thanks to the -std= option used. However, there doesn't seem to be an
option that doesn't cause some kind of error.

What does work though, is reducing the optimisation level, so just do
that. This is mostly for keeping CI happy, rather than people actively
using windows here.