run_tmb: Use -std=gnu++1y to avoid compilation problems under windows
"-std=c++1y" results in the following, when using g++ under windows:

D:/a/_temp/Library/TMB/include/tiny_ad/beta/toms708.cpp:40:33: error:
 'M_LN2' was not declared in this scope

Seems we need to change the standard.